// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/trackevent.proto

package com.luyun.whereareyou.shared;

public final class TrackEventProtos {
  private TrackEventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TrackEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.luyun.whereareyou.shared.TrackEvent.EventType type = 1 [default = START_TRACKING_REQ];
    boolean hasType();
    com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType getType();
    
    // optional int32 id = 2;
    boolean hasId();
    int getId();
    
    // optional string tracker = 3;
    boolean hasTracker();
    String getTracker();
    
    // optional string tracker_x = 4;
    boolean hasTrackerX();
    String getTrackerX();
    
    // optional string tracker_y = 5;
    boolean hasTrackerY();
    String getTrackerY();
    
    // optional string trackee = 6;
    boolean hasTrackee();
    String getTrackee();
    
    // optional string trackee_x = 7;
    boolean hasTrackeeX();
    String getTrackeeX();
    
    // optional string trackee_y = 8;
    boolean hasTrackeeY();
    String getTrackeeY();
  }
  public static final class TrackEvent extends
      com.google.protobuf.GeneratedMessage
      implements TrackEventOrBuilder {
    // Use TrackEvent.newBuilder() to construct.
    private TrackEvent(Builder builder) {
      super(builder);
    }
    private TrackEvent(boolean noInit) {}
    
    private static final TrackEvent defaultInstance;
    public static TrackEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public TrackEvent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.luyun.whereareyou.shared.TrackEventProtos.internal_static_com_luyun_whereareyou_shared_TrackEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.luyun.whereareyou.shared.TrackEventProtos.internal_static_com_luyun_whereareyou_shared_TrackEvent_fieldAccessorTable;
    }
    
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      START_TRACKING_REQ(0, 120),
      START_TRACKING_REP(1, 210),
      SEND_LOC_REQ(2, 320),
      SEND_LOC_REP(3, 230),
      QUERY_BY_ID_REQ(4, 321),
      QUERY_BY_ID_REP(5, 231),
      FWD_LOC_REQ(6, 211),
      FWD_LOC_REP(7, 121),
      ;
      
      public static final int START_TRACKING_REQ_VALUE = 120;
      public static final int START_TRACKING_REP_VALUE = 210;
      public static final int SEND_LOC_REQ_VALUE = 320;
      public static final int SEND_LOC_REP_VALUE = 230;
      public static final int QUERY_BY_ID_REQ_VALUE = 321;
      public static final int QUERY_BY_ID_REP_VALUE = 231;
      public static final int FWD_LOC_REQ_VALUE = 211;
      public static final int FWD_LOC_REP_VALUE = 121;
      
      
      public final int getNumber() { return value; }
      
      public static EventType valueOf(int value) {
        switch (value) {
          case 120: return START_TRACKING_REQ;
          case 210: return START_TRACKING_REP;
          case 320: return SEND_LOC_REQ;
          case 230: return SEND_LOC_REP;
          case 321: return QUERY_BY_ID_REQ;
          case 231: return QUERY_BY_ID_REP;
          case 211: return FWD_LOC_REQ;
          case 121: return FWD_LOC_REP;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final EventType[] VALUES = {
        START_TRACKING_REQ, START_TRACKING_REP, SEND_LOC_REQ, SEND_LOC_REP, QUERY_BY_ID_REQ, QUERY_BY_ID_REP, FWD_LOC_REQ, FWD_LOC_REP, 
      };
      
      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.luyun.whereareyou.shared.TrackEvent.EventType)
    }
    
    private int bitField0_;
    // required .com.luyun.whereareyou.shared.TrackEvent.EventType type = 1 [default = START_TRACKING_REQ];
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType getType() {
      return type_;
    }
    
    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    // optional string tracker = 3;
    public static final int TRACKER_FIELD_NUMBER = 3;
    private java.lang.Object tracker_;
    public boolean hasTracker() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTracker() {
      java.lang.Object ref = tracker_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tracker_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTrackerBytes() {
      java.lang.Object ref = tracker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tracker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string tracker_x = 4;
    public static final int TRACKER_X_FIELD_NUMBER = 4;
    private java.lang.Object trackerX_;
    public boolean hasTrackerX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getTrackerX() {
      java.lang.Object ref = trackerX_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          trackerX_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTrackerXBytes() {
      java.lang.Object ref = trackerX_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        trackerX_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string tracker_y = 5;
    public static final int TRACKER_Y_FIELD_NUMBER = 5;
    private java.lang.Object trackerY_;
    public boolean hasTrackerY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getTrackerY() {
      java.lang.Object ref = trackerY_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          trackerY_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTrackerYBytes() {
      java.lang.Object ref = trackerY_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        trackerY_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string trackee = 6;
    public static final int TRACKEE_FIELD_NUMBER = 6;
    private java.lang.Object trackee_;
    public boolean hasTrackee() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getTrackee() {
      java.lang.Object ref = trackee_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          trackee_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTrackeeBytes() {
      java.lang.Object ref = trackee_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        trackee_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string trackee_x = 7;
    public static final int TRACKEE_X_FIELD_NUMBER = 7;
    private java.lang.Object trackeeX_;
    public boolean hasTrackeeX() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getTrackeeX() {
      java.lang.Object ref = trackeeX_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          trackeeX_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTrackeeXBytes() {
      java.lang.Object ref = trackeeX_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        trackeeX_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string trackee_y = 8;
    public static final int TRACKEE_Y_FIELD_NUMBER = 8;
    private java.lang.Object trackeeY_;
    public boolean hasTrackeeY() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getTrackeeY() {
      java.lang.Object ref = trackeeY_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          trackeeY_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTrackeeYBytes() {
      java.lang.Object ref = trackeeY_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        trackeeY_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType.START_TRACKING_REQ;
      id_ = 0;
      tracker_ = "";
      trackerX_ = "";
      trackerY_ = "";
      trackee_ = "";
      trackeeX_ = "";
      trackeeY_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTrackerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTrackerXBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTrackerYBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTrackeeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTrackeeXBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getTrackeeYBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTrackerBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTrackerXBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTrackerYBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTrackeeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTrackeeXBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTrackeeYBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.luyun.whereareyou.shared.TrackEventProtos.TrackEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.luyun.whereareyou.shared.TrackEventProtos.internal_static_com_luyun_whereareyou_shared_TrackEvent_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.luyun.whereareyou.shared.TrackEventProtos.internal_static_com_luyun_whereareyou_shared_TrackEvent_fieldAccessorTable;
      }
      
      // Construct using com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType.START_TRACKING_REQ;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        tracker_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        trackerX_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        trackerY_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        trackee_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        trackeeX_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        trackeeY_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.getDescriptor();
      }
      
      public com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent getDefaultInstanceForType() {
        return com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.getDefaultInstance();
      }
      
      public com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent build() {
        com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent buildPartial() {
        com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent result = new com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tracker_ = tracker_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.trackerX_ = trackerX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.trackerY_ = trackerY_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.trackee_ = trackee_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.trackeeX_ = trackeeX_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.trackeeY_ = trackeeY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent) {
          return mergeFrom((com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent other) {
        if (other == com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTracker()) {
          setTracker(other.getTracker());
        }
        if (other.hasTrackerX()) {
          setTrackerX(other.getTrackerX());
        }
        if (other.hasTrackerY()) {
          setTrackerY(other.getTrackerY());
        }
        if (other.hasTrackee()) {
          setTrackee(other.getTrackee());
        }
        if (other.hasTrackeeX()) {
          setTrackeeX(other.getTrackeeX());
        }
        if (other.hasTrackeeY()) {
          setTrackeeY(other.getTrackeeY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType value = com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              tracker_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              trackerX_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              trackerY_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              trackee_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              trackeeX_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              trackeeY_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.luyun.whereareyou.shared.TrackEvent.EventType type = 1 [default = START_TRACKING_REQ];
      private com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType type_ = com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType.START_TRACKING_REQ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType getType() {
        return type_;
      }
      public Builder setType(com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.EventType.START_TRACKING_REQ;
        onChanged();
        return this;
      }
      
      // optional int32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string tracker = 3;
      private java.lang.Object tracker_ = "";
      public boolean hasTracker() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTracker() {
        java.lang.Object ref = tracker_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tracker_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTracker(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tracker_ = value;
        onChanged();
        return this;
      }
      public Builder clearTracker() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tracker_ = getDefaultInstance().getTracker();
        onChanged();
        return this;
      }
      void setTracker(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        tracker_ = value;
        onChanged();
      }
      
      // optional string tracker_x = 4;
      private java.lang.Object trackerX_ = "";
      public boolean hasTrackerX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTrackerX() {
        java.lang.Object ref = trackerX_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          trackerX_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTrackerX(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        trackerX_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrackerX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        trackerX_ = getDefaultInstance().getTrackerX();
        onChanged();
        return this;
      }
      void setTrackerX(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        trackerX_ = value;
        onChanged();
      }
      
      // optional string tracker_y = 5;
      private java.lang.Object trackerY_ = "";
      public boolean hasTrackerY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getTrackerY() {
        java.lang.Object ref = trackerY_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          trackerY_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTrackerY(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        trackerY_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrackerY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trackerY_ = getDefaultInstance().getTrackerY();
        onChanged();
        return this;
      }
      void setTrackerY(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        trackerY_ = value;
        onChanged();
      }
      
      // optional string trackee = 6;
      private java.lang.Object trackee_ = "";
      public boolean hasTrackee() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getTrackee() {
        java.lang.Object ref = trackee_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          trackee_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTrackee(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        trackee_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrackee() {
        bitField0_ = (bitField0_ & ~0x00000020);
        trackee_ = getDefaultInstance().getTrackee();
        onChanged();
        return this;
      }
      void setTrackee(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        trackee_ = value;
        onChanged();
      }
      
      // optional string trackee_x = 7;
      private java.lang.Object trackeeX_ = "";
      public boolean hasTrackeeX() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getTrackeeX() {
        java.lang.Object ref = trackeeX_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          trackeeX_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTrackeeX(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        trackeeX_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrackeeX() {
        bitField0_ = (bitField0_ & ~0x00000040);
        trackeeX_ = getDefaultInstance().getTrackeeX();
        onChanged();
        return this;
      }
      void setTrackeeX(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        trackeeX_ = value;
        onChanged();
      }
      
      // optional string trackee_y = 8;
      private java.lang.Object trackeeY_ = "";
      public boolean hasTrackeeY() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getTrackeeY() {
        java.lang.Object ref = trackeeY_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          trackeeY_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTrackeeY(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        trackeeY_ = value;
        onChanged();
        return this;
      }
      public Builder clearTrackeeY() {
        bitField0_ = (bitField0_ & ~0x00000080);
        trackeeY_ = getDefaultInstance().getTrackeeY();
        onChanged();
        return this;
      }
      void setTrackeeY(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        trackeeY_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.luyun.whereareyou.shared.TrackEvent)
    }
    
    static {
      defaultInstance = new TrackEvent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.luyun.whereareyou.shared.TrackEvent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_luyun_whereareyou_shared_TrackEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_luyun_whereareyou_shared_TrackEvent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/trackevent.proto\022\034com.luyun.wher" +
      "eareyou.shared\"\220\003\n\nTrackEvent\022T\n\004type\030\001 " +
      "\002(\01622.com.luyun.whereareyou.shared.Track" +
      "Event.EventType:\022START_TRACKING_REQ\022\n\n\002i" +
      "d\030\002 \001(\005\022\017\n\007tracker\030\003 \001(\t\022\021\n\ttracker_x\030\004 " +
      "\001(\t\022\021\n\ttracker_y\030\005 \001(\t\022\017\n\007trackee\030\006 \001(\t\022" +
      "\021\n\ttrackee_x\030\007 \001(\t\022\021\n\ttrackee_y\030\010 \001(\t\"\261\001" +
      "\n\tEventType\022\026\n\022START_TRACKING_REQ\020x\022\027\n\022S" +
      "TART_TRACKING_REP\020\322\001\022\021\n\014SEND_LOC_REQ\020\300\002\022" +
      "\021\n\014SEND_LOC_REP\020\346\001\022\024\n\017QUERY_BY_ID_REQ\020\301\002",
      "\022\024\n\017QUERY_BY_ID_REP\020\347\001\022\020\n\013FWD_LOC_REQ\020\323\001" +
      "\022\017\n\013FWD_LOC_REP\020yB0\n\034com.luyun.wherearey" +
      "ou.sharedB\020TrackEventProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_luyun_whereareyou_shared_TrackEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_luyun_whereareyou_shared_TrackEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_luyun_whereareyou_shared_TrackEvent_descriptor,
              new java.lang.String[] { "Type", "Id", "Tracker", "TrackerX", "TrackerY", "Trackee", "TrackeeX", "TrackeeY", },
              com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.class,
              com.luyun.whereareyou.shared.TrackEventProtos.TrackEvent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
